<map id="CADTools.CADToolsControl.CADToolsControl" name="CADTools.CADToolsControl.CADToolsControl">
<area shape="rect" id="node2" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a3509846f8c3321ad8d53729add5d996b" title="Required method for Designer support &#45; do not modify the contents of this method with the code editor..." alt="" coords="240,637,427,678"/>
<area shape="rect" id="node4" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a1b56c8c42fdbe9f93ad1ccd1a5483b15" title="CADTools.CADToolsControl.\lListDirectory" alt="" coords="780,245,967,286"/>
<area shape="rect" id="node3" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a719ee6ba22183d65242fa68bc9b4b897" title="CADTools.CADToolsControl.tab\lPage1_Enter" alt="" coords="487,49,693,90"/>
<area shape="rect" id="node7" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#abe2a2abc59ba200d91ada2d9b199ebdc" title="CADTools.CADToolsControl.button5\l_Click" alt="" coords="475,179,705,221"/>
<area shape="rect" id="node8" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#aefe34555bbba977fea0742200a0ea24c" title="CADTools.CADToolsControl.tree\lView1_MouseDoubleClick" alt="" coords="485,637,695,678"/>
<area shape="rect" id="node11" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a4d4dd41ec5a8c1636b559d0637c27da9" title="CADTools.CADToolsControl.tab\lPage2_Enter" alt="" coords="487,245,693,286"/>
<area shape="rect" id="node12" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a15c7ad49dbef31e10cc7c629729c7591" title="CADTools.CADToolsControl.tree\lView2_AfterSelect" alt="" coords="485,506,695,547"/>
<area shape="rect" id="node19" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#ae13acfef26a894f193683af0bec80659" title="CADTools.CADToolsControl.tree\lView2_MouseDoubleClick" alt="" coords="485,702,695,743"/>
<area shape="rect" id="node23" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a28a51d8e992b248f4d8961d524d9eb44" title="CADTools.CADToolsControl.picture\lBox2_MouseDoubleClick" alt="" coords="477,1029,703,1070"/>
<area shape="rect" id="node24" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#af47b115d5d31894098a9feee0a596c03" title="CADTools.CADToolsControl.button6\l_Click" alt="" coords="475,310,705,351"/>
<area shape="rect" id="node25" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a606a8c60673cac58efb184af0ce40fe2" title="CADTools.CADToolsControl.tab\lPage3_Enter" alt="" coords="487,1094,693,1135"/>
<area shape="rect" id="node29" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a68664cff274c4e441e34c162e76598c9" title="CADTools.CADToolsControl.button3\l_Click" alt="" coords="475,898,705,939"/>
<area shape="rect" id="node30" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a9ef6e0a3a7d61806965762d98cd5ed15" title="CADTools.CADToolsControl.button2\l_Click" alt="" coords="475,963,705,1005"/>
<area shape="rect" id="node31" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a4cb4e7d2a91eb2f7689bca511b7a1065" title="CADTools.CADToolsControl.button1\l_Click_1" alt="" coords="475,1225,705,1266"/>
<area shape="rect" id="node34" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a21be61e91072306b137c442f514b3fb0" title="CADTools.CADToolsControl.tree\lView3_NodeMouseClick" alt="" coords="485,1159,695,1201"/>
<area shape="rect" id="node35" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a5b43c3e6ceb00993f449de9f94c661d6" title="CADTools.CADToolsControl.tab\lPage4_Enter" alt="" coords="487,375,693,417"/>
<area shape="rect" id="node36" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a5553a5de7a9006bd20d2b521d1c94227" title="CADTools.CADToolsControl.tree\lView4_MouseDoubleClick" alt="" coords="485,571,695,613"/>
<area shape="rect" id="node38" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#afd9335b2320db3a004053fe8541b67d8" title="CADTools.CADToolsControl.button7\l_Click" alt="" coords="475,1290,705,1331"/>
<area shape="rect" id="node40" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a1292ed594d996f9dc98edef10e7e2214" title="CADTools.CADToolsControl.button4\l_MouseUp" alt="" coords="475,833,705,874"/>
<area shape="rect" id="node43" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a38b017976c734c3bb653d9562c4407a0" title="CADTools.CADToolsControl.text\lBox1_MouseUp" alt="" coords="485,767,695,809"/>
<area shape="rect" id="node44" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a4ca1c138f140b64f6453197bbf558446" title="CADTools.CADToolsControl.button8\l_Click" alt="" coords="475,441,705,482"/>
<area shape="rect" id="node45" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#ada51e79a953f23c8fcdad7a0ab68e23e" title="CADTools.CADToolsControl.\lCADToolsControl_SizeChanged" alt="" coords="487,114,693,155"/>
<area shape="rect" id="node5" href="$class_c_a_d_tools_1_1model_1_1_model.html#a2c3d5e865f0d92acfb35ddd57b96a766" title="CADTools.model.Model.IsLoaded" alt="" coords="1043,227,1258,253"/>
<area shape="rect" id="node6" href="$class_c_a_d_tools_1_1model_1_1_model.html#a30c13d72a0bd9f01931b72580be04378" title="Method to read the Library paths from the CADTools config file and set the required paths..." alt="" coords="1044,277,1257,304"/>
<area shape="rect" id="node9" href="$class_c_a_d_tools_1_1model_1_1_data_node.html#acf7c556b062fa44f5d871ed1719b56f8" title="Returns Dataode type as string. " alt="" coords="781,611,965,653"/>
<area shape="rect" id="node10" href="$class_c_a_d_tools_1_1_win_utilities.html#a035aeba61cb4218e911e8d9ea7649868" title="CADTools.WinUtilities.Open\lShortcut" alt="" coords="781,677,966,718"/>
<area shape="rect" id="node13" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#afe844faee7ebb65f3cdb7a3de8b7e810" title="CADTools.ACADConnector.Get\lOuterDWGModelBitmap" alt="" coords="771,481,975,522"/>
<area shape="rect" id="node14" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a466a24ee8d98ecb5aed258b0c6f08c14" title="CADTools.ACADConnector.Get\lBlockImage" alt="" coords="1049,415,1253,457"/>
<area shape="rect" id="node17" href="$class_c_a_d_tools_1_1_win_utilities.html#a11e38744132fafc5df6e46d5bcb2d6f9" title="CADTools.WinUtilities.Image\lSourceToGDI" alt="" coords="1056,481,1245,522"/>
<area shape="rect" id="node18" href="$class_c_a_d_tools_1_1_win_utilities.html#abcfefc99a601e3c6694c79f0bb0a9191" title="CADTools.WinUtilities.Convert" alt="" coords="1052,547,1249,573"/>
<area shape="rect" id="node15" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a5972b36cc47d9c96143a476ef82449bd" title="CADTools.ACADConnector.Get\lBlockImagePointer" alt="" coords="1313,415,1517,457"/>
<area shape="rect" id="node16" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a57ac13461a7f78354275634721e6db92" title="CADTools.ACADConnector.Get\lBlockTableRecordId" alt="" coords="1571,415,1775,457"/>
<area shape="rect" id="node20" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#ad413036030d974d9486ed1bbea05d6fa" title="CADTools.ACADConnector.Insert\lBlock" alt="" coords="766,742,981,783"/>
<area shape="rect" id="node21" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a8c447ee8b5a788e3768eb93a59788a3d" title="CADTools.ACADConnector.Write\lCADMessage" alt="" coords="1308,777,1523,818"/>
<area shape="rect" id="node22" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a3435d754a21c604c888674c308925467" title="the source drawig should be drawn as number of separate entites with or without attributes. Throws NotImplementedException if invoked with .dxf file " alt="" coords="1041,718,1260,759"/>
<area shape="rect" id="node26" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#ac63a9d01b8d36b26ed62f9d0866198d2" title="CADTools.CADToolsControl.\lLoadLayers" alt="" coords="780,958,967,999"/>
<area shape="rect" id="node27" href="$class_c_a_d_tools_1_1model_1_1_layers.html#a0281bab7185289faa7e3ed7d89b4595e" title="CADTools.model.Layers.ReadFile" alt="" coords="1042,912,1259,939"/>
<area shape="rect" id="node28" href="$class_c_a_d_tools_1_1model_1_1_layers.html#a6342310dac1c90ffd3e805cfc7d66571" title="CADTools.model.Layers.Populate" alt="" coords="1042,963,1259,989"/>
<area shape="rect" id="node32" href="$class_c_a_d_tools_1_1model_1_1_layers.html#acb0cc679023f04693bfbbf2fb73bd299" title="CADTools.model.Layers.Create\lLayers" alt="" coords="771,1225,975,1266"/>
<area shape="rect" id="node33" href="$class_c_a_d_tools_1_1model_1_1_layer_node.html#a381d09a7330b97c339d8f92ec221cb49" title="CADTools.model.LayerNode.\lCreateCADLayer" alt="" coords="1056,1225,1245,1266"/>
<area shape="rect" id="node37" href="$class_c_a_d_tools_1_1_win_utilities.html#a1c4dee71704b9c8d91dce06da66c8dfa" title="CADTools.WinUtilities.Open\lWithDefaultProgram" alt="" coords="781,546,966,587"/>
<area shape="rect" id="node39" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a97368a09488030fdcaebbac6877cc034" title="CADTools.ACADConnector.OpenPDF" alt="" coords="753,1297,993,1324"/>
<area shape="rect" id="node41" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#abe6dd55212610a3686a22659cea250cd" title="CADTools.ACADConnector.Open\lHTTPS" alt="" coords="766,833,981,874"/>
<area shape="rect" id="node42" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a996e964831dcba4da1f2d522e5d551d6" title="CADTools.ACADConnector.Page\lExists" alt="" coords="1044,835,1257,877"/>
</map>
