<map id="CADTools.ACADConnector.GetOuterDWGModelBitmap" name="CADTools.ACADConnector.GetOuterDWGModelBitmap">
<area shape="rect" id="node2" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a466a24ee8d98ecb5aed258b0c6f08c14" title="CADTools.ACADConnector.Get\lBlockImage" alt="" coords="257,5,461,47"/>
<area shape="rect" id="node5" href="$class_c_a_d_tools_1_1_win_utilities.html#a11e38744132fafc5df6e46d5bcb2d6f9" title="CADTools.WinUtilities.Image\lSourceToGDI" alt="" coords="265,71,454,112"/>
<area shape="rect" id="node6" href="$class_c_a_d_tools_1_1_win_utilities.html#abcfefc99a601e3c6694c79f0bb0a9191" title="CADTools.WinUtilities.Convert" alt="" coords="261,137,458,163"/>
<area shape="rect" id="node3" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a5972b36cc47d9c96143a476ef82449bd" title="CADTools.ACADConnector.Get\lBlockImagePointer" alt="" coords="509,5,713,47"/>
<area shape="rect" id="node4" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a57ac13461a7f78354275634721e6db92" title="CADTools.ACADConnector.Get\lBlockTableRecordId" alt="" coords="761,5,965,47"/>
</map>
