<map id="CADTools.ACADConnector.GetBlockTableRecordId" name="CADTools.ACADConnector.GetBlockTableRecordId">
<area shape="rect" id="node2" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a5972b36cc47d9c96143a476ef82449bd" title="CADTools.ACADConnector.Get\lBlockImagePointer" alt="" coords="257,39,461,80"/>
<area shape="rect" id="node3" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#a466a24ee8d98ecb5aed258b0c6f08c14" title="CADTools.ACADConnector.Get\lBlockImage" alt="" coords="509,5,713,47"/>
<area shape="rect" id="node8" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#ad8c89d25923fb0d15eb1ad15e61eb9a3" title="CADTools.ACADConnector.Get\lImageSource" alt="" coords="509,71,713,112"/>
<area shape="rect" id="node4" href="$class_c_a_d_tools_1_1_a_c_a_d_connector.html#afe844faee7ebb65f3cdb7a3de8b7e810" title="CADTools.ACADConnector.Get\lOuterDWGModelBitmap" alt="" coords="761,5,965,47"/>
<area shape="rect" id="node5" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a15c7ad49dbef31e10cc7c629729c7591" title="CADTools.CADToolsControl.tree\lView2_AfterSelect" alt="" coords="1013,5,1223,47"/>
<area shape="rect" id="node6" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a3509846f8c3321ad8d53729add5d996b" title="Required method for Designer support &#45; do not modify the contents of this method with the code editor..." alt="" coords="1271,5,1457,47"/>
<area shape="rect" id="node7" href="$class_c_a_d_tools_1_1_c_a_d_tools_control.html#a48a6ded0e3a679b9d83ea3f9461a00f9" title="CADTools.CADToolsControl.\lCADToolsControl" alt="" coords="1505,5,1692,47"/>
</map>
